export const NOTIFY_TURN_ACTIVE = "NOTIFY_TURN_ACTIVE";
export const COMPLETE_TURN = "COMPLETE_TURN";
export const EXPIRE_TURN = "EXPIRE_TURN";
export const RECEIVE_TURNS = "RECEIVE_TURNS";
export const TURNS_RECEIVED = "TURNS_RECEIVED";
